[tool.black]
line-length = 110
target-version = ['py310']
ignore = ['F841', 'F401', 'E501']

[tool.ruff]
line-length = 110
target-version = 'py310'
ignore = ['F841', 'F401', 'E501']

[tool.ruff.isort]
combine-as-imports = true
force-wrap-aliases = true

[tool.pyright]
include = ['src/**']
exclude = ['/usr/lib/**']
